version: '3.7'
networks:
  localnetwork:
    driver: bridge
    ipam:
      driver: default
services:
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/host.key:/etc/nginx/certs/ssl.key
      - ./nginx/host.crt:/etc/nginx/certs/ssl-unified.crt
    networks:
      - localnetwork      
    ports:
      - "443:443"

  varnish:
    build: ./varnish
    container_name: varnish
    ports:
      - "9012:80"
    depends_on:
      - nginx
    restart: unless-stopped
    networks:
      - localnetwork
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    environment:
      VARNISH_BACKEND_GRACE: 10m
      VARNISH_BACKEND_HOST: nginx
      VARNISH_CACHE_STATIC_FILES: 1 #attivo ma non gestibile dal vcl iniettato
      VARNISH_DEFAULT_TTL: 300s
      VARNISH_ERRORS_GRACE: 60s

